def show_dic(check_port):
    service_port = {
        1   : "TCPMUX",
        7   : "ECHO",
        9   : "DISCARD",
        13  : "DAYTIME",
        21  : "FTP",
        22  : "SSH",
        23  : "TELNET",
        25  : "SMTP",
        42  : "NAMESERVER",
        67  : "DHCPS",
        43  : "WHOIS",
        70  : "GOPHER",
        53  : "DNS",
        80  : "HTTP",
        68  : "DHCPC",
        110 : "POP3",
        79  : "FINGER",
        123 : "NTP",
        109 : "POP2",
        137 : "NETBIOS-NS",
        113 : "IDENT",
        139 : "NETBIOS-SSN",
        135 : "RPC",
        161 : "SNMP",
        138 : "NETBIOS-DGM",
        179 : "BGP",
        143 : "IMAP",
        443 : "HTTPS",
        162 : "SNMPTRAP",
        465 : "SMTPS",
        389 : "LDAP",
        636 : "LDAPS",
        445 : "SMB",
        995 : "POP3S",
        587 : "SMTP-SUBMISSION",
        993 :  "IMAPS",
    }
    __service_checker = service_port.get(check_port, "Unknown")
    return __service_checker